### ISSUE TITLE
Bump Support HTTPX Version To 0.23

### ISSUE THREAD

**Issue by yooper** [renalreg/python-mirth-client#48]
Hello, 
I am trying to use your package on a project but the HTTPX dependency won't allow me to install. Is it possible to get the supported version of httpx updated to the most recent version 0.23. 

Here is the failure I am getting on install. 

```
  SolverProblemError

  Because mirth-client (3.0.0) depends on httpx (>=0.18,<0.23)
   and no versions of mirth-client match >3.0.0,<4.0.0, mirth-client (>=3.0.0,<4.0.0) requires httpx (>=0.18,<0.23).
  So, because fics-api depends on both httpx (^0.23) and mirth-client (^3.0.0), version solving failed.

```

**Comment by jtc42** [comment]
Resolved by https://github.com/renalreg/python-mirth-client/releases/tag/v3.1.0

Should be on PyPI as soon as https://github.com/renalreg/python-mirth-client/actions/runs/2622913640 has finished running

**Comment by yooper** [comment]
@jtc42 , thank you!
